#! /bin/bash -ev
cd $(dirname $0)

aws --endpoint-url=http://localhost:4581 \
  cloudformation create-stack \
  --stack-name sqs-test-stack \
  --template-body file://./sqs-template.json \
  --parameters file://./parameters.json \
  --output json
