version: '3'
services:
  localstack-sqs:
    environment:
      HOSTNAME: localhost
      DEFAULT_REGION: ap-southeast-2
      SERVICES: sqs:4576,cloudformation:4581
    image: localstack/localstack:0.8.6
    ports:
      - "0.0.0.0:4576:4576"
      - "0.0.0.0:4581:4581"
