#!/bin/bash -ex

cd $(dirname $0)/..

LAMBDA_BUCKEY_STACK_NAME="test-lambda-bucket-stack"
ENV=$(echo ${ENV:-${1:-"test"}} | tr '[A-Z]' '[a-z]')
AWS_DEFAULT_REGION=${2:-ap-southeast-2}

aws cloudformation deploy \
    --template-file ./deployment/s3/template.yml \
    --stack-name ${LAMBDA_BUCKEY_STACK_NAME} \
    --region ${AWS_DEFAULT_REGION} \
    --capabilities CAPABILITY_IAM \
    --parameter-overrides file://deployment/lambda/${ENV}.conf \
    --output json
