#! /bin/bash -ev
cd $(dirname $0)/..

AWS_ACCESS_KEY_ID=test-access-key-id \
AWS_SECRET_ACCESS_KEY=test-secret-key \
AWS_SECURITY_TOKEN=test-security-token \
AWS_SESSION_TOKEN=test-session-token \
AWS_REGION=${1:-ap-southeast-2} \
NODE_ENV=development \
    yarn start
