#!/bin/bash -evu
cd $(dirname $0)/..

if [[ $# -lt 2 ]]; then
  echo "No enough args!"
  echo "Usage: $0 START_DATE END_DATE ENV"
  echo "  START_DATE:  Start date (include, format: 2017-10-20),"
  echo "  END_DATE:    End date (exclude, format: 2017-11-20)."
  echo "  ENV:         Environment flag, should be one of test, staging or prod,"
  exit 1
fi

docker build -t athena-test .
echo ">>> Finished Building docker image athena-test with tag latest <<<"

ENV=$(echo ${3:-"test"} | tr "a-z" "A-Z")
docker run \
  --rm \
  -i \
  -v $(pwd)/result:/app/result \
  -e ENV=${ENV} \
  -e START_DATE=$1 \
  -e END_DATE=$2 \
  -e AWS_ACCESS_KEY_ID \
  -e AWS_SECRET_ACCESS_KEY \
  -e AWS_SECURITY_TOKEN \
  -e AWS_SESSION_TOKEN \
  --name athena-test-local \
  athena-test
