#! /bin/bash -ex
cd $(dirname $0)/..

CONTAINER_NAME=application-check-code-style

docker run --rm \
  -v $(pwd):/app \
  -e NODE_ENV=test \
  --name $CONTAINER_NAME node:8.11.3-alpine \
  sh -c "cd /app && yarn install && yarn eslint"
