#!/bin/bash -ex

cd $(dirname $0)/..

_usage() {
  echo "No enough args!!!"
  echo "Usage: ./$0 ENV [AWS_REGION]"
  exit 1
}

[[ $# -lt 1 ]] && _usage && exit 1

ENV=${1,,}
AWS_REGION=${2:-ap-southeast-2}
STACK_NAME=test-bucket-stack

aws cloudformation create-stack \
  --region ${AWS_REGION} \
  --stack-name ${STACK_NAME} \
  --template-body file://./deployment/s3/template.json \
  --parameter file://./deployment/s3/${ENV}.json
