env:
  node: true
  commonjs: true
  es6: true
  jest: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
ignorePatterns:
  - node_modules/
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  quote-props:
    - error
    - consistent-as-needed
  comma-dangle:
    - error
    - always-multiline
  object-curly-spacing:
    - error
    - always
