version: '3'
services:
  localstack-sqs:
    environment:
      DEFAULT_REGION: ap-southeast-2
      SERVICES: route53:4580,cloudformation:4581
    image: localstack/localstack:0.8.6
    ports:
      - "0.0.0.0:4580:4580"
      - "0.0.0.0:4581:4581"
