#!/usr/bin/env bash -e
cd $(dirname $0)/..

_usage() {
	echo "No enough args!!!"
	echo "Usage: ./$0 ENV [AWS_REGION]"
	exit 1
}

[[ $# -lt 1 ]] && _usage && exit 1

ENV=${1,,}
AWS_REGION=${2:-ap-southeast-2}
STACK_NAME=test-dns-stack
STACK_PARAM="deployment/route53/${ENV}.json"

if [ ! -e ${STACK_PARAM} ]; then
	echo "Param file ${STACK_PARAM} doesn't exist!"
	exit 2
fi

_stack_status() {
	status=$(
		aws cloudformation describe-stacks \
			--stack-name "${STACK_NAME}" \
			--query 'Stacks[]["StackStatus"][]' \
			--output text \
			2>/dev/null
	)
	[[ -z "${status}" ]] && return 1
	echo "${status}"
}

_stack_exists() {
	[[ ! -z "$(_stack_status)" ]]
	return $?
}

_wait_until_complete() {
	[[ $(_stack_status) =~ COMPLETE$ ]] && exit 0
	aws cloudformation wait stack-${ACTION}-complete \
		--stack-name "${STACK_NAME}" \
		&>/dev/null
}

_stack_exists && ACTION="update" || ACTION="create"

if [[ ! $(_stack_status) =~ IN_PROGRESS$ ]]; then
	aws cloudformation ${ACTION}-stack \
		--stack-name ${STACK_NAME} \
		--template-body file://deployment/route53/template.json \
		--parameters file://${STACK_PARAM} \
		--region ${AWS_REGION} 2>&1
fi

echo "Waiting for stack to ${ACTION}"
_wait_until_complete
